//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBEngine
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        public int InvoiceID { get; set; }
        public string InvoiceNumber { get; set; }
        public string InvoiceOrderNumber { get; set; }
        public int CustomerID { get; set; }
        public string InvoiceDescription { get; set; }
        public decimal InvoiceTaxable { get; set; }
        public decimal InvoiceTax { get; set; }
        public decimal InvoiceDue { get; set; }
        public int StatusID { get; set; }
        public System.DateTime InvoiceCreationDate { get; set; }
        public System.DateTime InvoiceDueDate { get; set; }
        public string InvoiceActive { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Status Status { get; set; }
    }
}
