//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBEngine
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoices
    {
        public int InvoiceID { get; set; }
        public string InvoiceNumber { get; set; }
        public string InvoiceOrderNumber { get; set; }
        public int CustomerID { get; set; }
        public string InvoiceDescription { get; set; }
        public decimal InvoiceTaxable { get; set; }
        public decimal InvoiceTax { get; set; }
        public decimal InvoiceDue { get; set; }
        public int StatusID { get; set; }
        public System.DateTime InvoiceCreationDate { get; set; }
        public System.DateTime InvoiceDueDate { get; set; }
        public string InvoiceActive { get; set; }
    
        public virtual Customers Customers { get; set; }
        public virtual Status Status { get; set; }
    }
}
