//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBEngine
{
    using System;
    using System.Collections.Generic;
    
    public partial class Session
    {
        public int SessionID { get; set; }
        public int UserID { get; set; }
        public string SessionToken { get; set; }
        public System.DateTime SessionExpire { get; set; }
    
        public virtual User User { get; set; }
    }
}
